language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip mock h5py lxml nose numpy numba scipy matplotlib pandas
  - source activate test-environment
  - pip install python-coveralls

  - pip install .
services:
  - xvfb
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - nosetests --with-coverage --cover-package=corrosion-profiler --logging-level=INFO

after_success:
  - coveralls
  # Your test script goes here
